name: CI/CD Pipeline

on:
  push:
    branches: [ develop, ci/ci-cd ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      # 소스 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # application.yml 생성 및 Secrets 내용 반영
      - name: Make application.yml
        run: |
          cd ./src/main/resources
          touch application.yml
          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml
        shell: bash

      # Gradle 빌드 수행
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # EC2에 jar 파일 전송 및 배포
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu # Ubuntu 사용자명
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          # EC2에 애플리케이션 디렉터리 생성
          ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} 'mkdir -p /opt/myapp'
          # JAR 파일 전송
          scp -i private_key -o StrictHostKeyChecking=no build/libs/*.jar ${USER}@${HOST}:/opt/myapp/app.jar
          # 애플리케이션 배포
          ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
            sudo systemctl stop myapp || true
            sudo mv /opt/myapp/app.jar /opt/myapp/app.jar
            sudo systemctl start myapp
